# Generated by Django 3.0.7 on 2020-09-15 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('student_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('time_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('teacher_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('time_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
